// Generated by vovk-cli v0.0.1-draft.398 at 2025-11-07T09:39:50.258Z
import type { VovkFetcher } from "vovk";
import { createRPC } from "vovk";
import { schema } from "./schema";

import type { Controllers as Controllers0 } from "../../app/api/static/[[...vovk]]/route.ts";

export const OpenApiRPC = createRPC<
  Controllers0["OpenApiRPC"],
  typeof import("vovk").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "static", "OpenApiRPC", import("vovk"), {
  validateOnClient: import("vovk-ajv"),
});

export { schema };
