// Generated by vovk-cli v0.0.1 at 2026-03-16T15:43:39.556Z

import { createRPC } from 'vovk/createRPC';
import type { VovkFetcher } from 'vovk/fetcher';
import type { Controllers as Controllers0 } from '../../app/api/static/[[...vovk]]/route.ts';
import { schema } from './schema';

export const OpenApiRPC = createRPC<
  Controllers0['OpenApiRPC'],
  typeof import('vovk/fetcher').fetcher extends VovkFetcher<infer U> ? U : never
>(schema, 'static', 'OpenApiRPC', import('vovk/fetcher'), {
  validateOnClient: import('vovk-ajv'),
});

export { schema };
