// Generated by vovk-cli v0.0.1-draft.394 at 2025-11-06T06:54:36.224Z
import type { VovkFetcher } from "vovk";
import { createRPC } from "vovk";
import { schema } from "./schema";

// import { openapi } from './openapi';
// TODO: This is a temporary fix for https://github.com/rolldown/tsdown/issues/528#issuecomment-3476284358
import openapi from "./openapi.json" with { type: "json" };

import type { Controllers as Controllers0 } from "../../app/api/static/[[...vovk]]/route.ts";

export const OpenApiRPC = createRPC<
  Controllers0["OpenApiRPC"],
  typeof import("vovk").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "static", "OpenApiRPC", import("vovk"), {
  validateOnClient: import("vovk-ajv"),
  apiRoot: "http://localhost:3000/api",
});

export { schema, openapi };
