// auto-generated by vovk-cli v0.0.1-draft.345 at 2025-08-28T19:38:14.080Z

import meta from "./../../../.vovk-schema/_meta.json" with { type: "json" };

import segment0 from "./../../../.vovk-schema/static.json" with { type: "json" };

const segments = {
  static: segment0,
};

export const schema = {
  $schema: "https://vovk.dev/api/schema/v3/schema.json",
  segments,
  meta: {
    ...meta,
  },
};
