// auto-generated by vovk-cli v0.0.1-draft.372 at 2025-10-03T07:44:36.825Z

import segment0 from "./../../../.vovk-schema/static.json" with { type: "json" };

import meta from "./../../../.vovk-schema/_meta.json" with { type: "json" };

const segments = {
  static: segment0,
};

export const schema = {
  $schema: "https://vovk.dev/api/schema/v3/schema.json",
  segments,
  meta,
};
