// auto-generated by vovk-cli v0.0.1-draft.329 at 2025-08-08T13:44:57.700Z

import meta from './../../../.vovk-schema/_meta.json' with { type: "json" };



import segment0 from './../../../.vovk-schema/static.json' with { type: "json" };

const segments = {
  'static': segment0,
  
};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta: {
    $schema: 'https://vovk.dev/api/schema/v3/meta.json',
    apiRoot: 'http://localhost:3000/api', // for debugging purposes
    
    ...meta,
    
  }
};

