
[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

[project]
name = "vovk_hello_world_demo"
version = "0.0.0"
description = ""
requires-python = ">=3.7"
dependencies = [
    "vovk_hello_world @ file:///../dist_python",
]