// auto-generated by Vovk.ts 2025-07-11T15:54:22.419Z
import type { VovkClientFetcher } from 'vovk';
import { fetcher } from 'vovk';
import { createRPC } from 'vovk-react-query';
import { schema } from './schema';

import type { Controllers as Controllers0 } from "../../app/api/[[...vovk]]/route.ts";

import { validateOnClient } from 'vovk-ajv';

type Options = typeof fetcher extends VovkClientFetcher<infer U> ? U : never;

export const UserRPC = createRPC<Controllers0["UserRPC"], Options>(
  schema, '', 'UserRPC', fetcher,
  { validateOnClient, apiRoot: 'http://localhost:3000/api' }
);

export const StreamRPC = createRPC<Controllers0["StreamRPC"], Options>(
  schema, '', 'StreamRPC', fetcher,
  { validateOnClient, apiRoot: 'http://localhost:3000/api' }
);

export { schema };
