// Generated by vovk-cli v0.0.1-draft.398 at 2025-11-07T09:39:50.258Z
import type { VovkFetcher } from "vovk";
import { createRPC } from "vovk";
import { schema } from "./schema";

import type { Controllers as Controllers0 } from "../../app/api/[[...vovk]]/route.ts";

export const UserRPC = createRPC<
  Controllers0["UserRPC"],
  typeof import("vovk").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "", "UserRPC", import("vovk"), {
  validateOnClient: import("vovk-ajv"),
});

export const StreamRPC = createRPC<
  Controllers0["StreamRPC"],
  typeof import("vovk").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "", "StreamRPC", import("vovk"), {
  validateOnClient: import("vovk-ajv"),
});

export { schema };
