// Generated by vovk-cli v0.0.1-beta.67 at 2026-01-11T19:00:32.706Z
import type { VovkFetcher } from "vovk/fetcher";
import { createRPC } from "vovk/createRPC";
import { schema } from "./schema";

import type { Controllers as Controllers0 } from "../../app/api/[[...vovk]]/route.ts";

export const UserRPC = createRPC<
  Controllers0["UserRPC"],
  typeof import("vovk/fetcher").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "", "UserRPC", import("vovk/fetcher"), {
  validateOnClient: import("vovk-ajv"),
});

export const StreamRPC = createRPC<
  Controllers0["StreamRPC"],
  typeof import("vovk/fetcher").fetcher extends VovkFetcher<infer U> ? U : never
>(schema, "", "StreamRPC", import("vovk/fetcher"), {
  validateOnClient: import("vovk-ajv"),
});

export { schema };
