// auto-generated by Vovk.ts 2025-07-11T15:54:22.419Z

import meta from './../../../.vovk-schema/_meta.json' with { type: "json" };



import segment0 from './../../../.vovk-schema/root.json' with { type: "json" };

const segments = {
  '': segment0,
  
};

export const schema = {
  $schema: 'https://vovk.dev/api/spec/v3/schema.json',
  segments,
  meta: {
    $schema: 'https://vovk.dev/api/spec/v3/meta.json',
    apiRoot: 'http://localhost:3000/api', // for debugging purposes
    
    ...meta,
    
  }
};

