// Generated by vovk-cli v0.0.1 at 2026-03-16T15:43:39.562Z

import meta from './../../../.vovk-schema/_meta.json' with { type: 'json' };
import segment0 from './../../../.vovk-schema/root.json' with { type: 'json' };

const segments = {
  '': segment0,
};

export const schema = {
  $schema: 'https://vovk.dev/api/schema/v3/schema.json',
  segments,
  meta,
};
