// Generated by vovk-cli v0.2.0 at 2026-06-12T08:57:51.887Z

import segment0 from "./../../../.vovk-schema/root.json" with { type: "json" };

import meta from "./../../../.vovk-schema/_meta.json" with { type: "json" };

const segments = {
  "": segment0,
};

export const schema = {
  $schema: "https://vovk.dev/api/schema/v3/schema.json",
  segments,
  meta,
};
