// auto-generated by vovk-cli v0.0.1-draft.375 at 2025-10-03T08:53:27.434Z
import type { VovkFetcher } from 'vovk';
import { createRPC } from 'vovk';
import { schema } from './schema';
import { openapi } from './openapi';

import type { Controllers as Controllers0 } from "../src/app/api/[[...vovk]]/route.ts";

import type { Controllers as Controllers1 } from "../src/app/api/static/[[...vovk]]/route.ts";

   

export const UserRPC = createRPC<Controllers0["UserRPC"], typeof import('vovk').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'UserRPC', import('vovk'),
  { validateOnClient: import('vovk-ajv'), apiRoot: 'https://hello-world.vovk.dev/api' }
);

export const StreamRPC = createRPC<Controllers0["StreamRPC"], typeof import('vovk').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, '', 'StreamRPC', import('vovk'),
  { validateOnClient: import('vovk-ajv'), apiRoot: 'https://hello-world.vovk.dev/api' }
);

export const OpenApiRPC = createRPC<Controllers1["OpenApiRPC"], typeof import('vovk').fetcher extends VovkFetcher<infer U> ? U : never>(
  schema, 'static', 'OpenApiRPC', import('vovk'),
  { validateOnClient: import('vovk-ajv'), apiRoot: 'https://hello-world.vovk.dev/api' }
);

export { schema, openapi };
