[package]
name = "vovk_showcase_demo"
version = "0.0.0"
edition = "2021"

# No dependencies needed for basic testing
[dependencies]
vovk_showcase = { path = "../dist_rust" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
